version: "3.18"

services:
  mongodb-server:
    container_name: mongodb-server
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ariafatah
      MONGO_INITDB_ROOT_PASSWORD: ariafatah
      MONGO_INITDB_DATABASE: admin
    networks:
      - net-mongo
  mongodb-express-web:
    container_name: mongodb-express-web
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ariafatah
      ME_CONFIG_MONGODB_ADMINPASSWORD: ariafatah
      ME_CONFIG_MONGODB_SERVER: mongodb-server
    networks:
      - net-mongo
    depends_on:
      - mongodb-server

networks:
  net-mongo:
    name: net-mongo
    driver: bridge