version: '3.9'

services:
  mongodb-harbas:
    container_name: mongodb-harbas
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ariafatah
      MONGO_INITDB_ROOT_PASSWORD: ariafatah
      MONGO_INITDB_DATABASE: admin
    networks:
      - network-harbas

networks:
  network-harbas:
    name: network-harbas
    driver: bridge
